### PR TITLE
Use "release" build profile, since "optimized" contains -march=native

### PR DESCRIPTION
**Pull request by larseggert**
See https://www.nsnam.org/docs/tutorial/html/getting-started.html#id1

### CODE REVIEW

**Comment by marten-seemann** [comment]
What’s the difference?

**Comment by larseggert** [comment]
`-march=native` generates code specifically optimized for the CPU the build runs on, which may not be portable to all other CPUs.

**Comment by larseggert** [comment]
It's what you want to use when you know you will only run locally (or on one CPU stepping), but not a good idea for shipping a container.

**Comment by marten-seemann** [comment]
Thank you, that sounds reasonable. The Docker build on CI seems to be failing though.

**Pull request merged**
